### ISSUE TITLE
Genesect Gen8 sprite inconsistency / missing Appletun-Gmax / contribution question(s)

### ISSUE THREAD

**Issue by PTGigi** [msikma/pokesprite#110]
Hello! Items 1-3 on the list below seemed small enough that I could contribute a fix, I just wanted to double check 1 and 3 before making a pull request. 

1. In the pokemon-gen8 folder, the regular folder has just one Genesect sprite
![regular/genesect.png](https://raw.githubusercontent.com/msikma/pokesprite/master/pokemon-gen8/regular/genesect.png) [genesect.png](https://github.com/msikma/pokesprite/blob/master/pokemon-gen8/regular/genesect.png)
While the shiny folder has two. The genesect-standard.png is the old, smaller sprite however. 
![regular/genesect.png](https://raw.githubusercontent.com/msikma/pokesprite/master/pokemon-gen8/shiny/genesect.png) [genesect.png](https://github.com/msikma/pokesprite/blob/master/pokemon-gen8/shiny/genesect.png) ![regular/genesect.png](https://raw.githubusercontent.com/msikma/pokesprite/master/pokemon-gen8/shiny/genesect-standard.png) [genesect-standard.png](https://github.com/msikma/pokesprite/blob/master/pokemon-gen8/shiny/genesect-standard.png)
~~Would it be preferred to remove the shiny/genesect-standard.png variant entirely or update it to the Gen8 sprite (and add it to the regular folder as well)?~~ See comment below
2. Appletun-Gmax is missing. These would be the same sprites as Flapple-Gmax.
3. For my own projects, I created a recolor of [Arceus ??? (the glitch/unavailable Arceus form)](https://bulbapedia.bulbagarden.net/wiki/%3F%3F%3F_(type)#Arceus). I'd be happy to add it to this project if wanted ![Arceus ???](https://ptgigi.com/apps/pokemon/img/icon/arceus-unknown.png) ![shiny Arceus ???](https://ptgigi.com/apps/pokemon/img/icon/shiny/arceus-unknown.png)
4. I'd also be grateful if you would add my [Random Pokemon Generator](https://ptgigi.com/apps/pokemon/randomizer/) to the list of projects using pokesprite. I'm also releasing a second project using this repo's icons soon (next week if not this month) and have plans for more projects that would use icons from this repo, so it you prefer I have a [projects page here where I list all my projects](https://ptgigi.com/code/). Otherwise, I can make a new request when I release a new project using these sprites. 

Thank you!

**Comment by PTGigi** [comment]
1. Upon further investigation, it seems like genesect-standard.png shouldn't exist as -standard is an alias of genesect.png for Gen8, so I'll remove the shiny/genesect-standard.png sprite unless otherwise stated.
2. _(ignore this line, github keeps converting the 3. to a 2. if I don't include this)_
3. I've noticed there's an existing Arceus Unknown entry, but it is an alias of Arceus Normal. If the sprites are wanted, can I replace the alias with the sprites above or should I use a different suffix for this form?

**Comment by msikma** [comment]
Good catch! Yeah, I'm actually a little bit confused by the Genesect sprite now because originally the "standard" icon was, I think, actually different. But I don't remember exactly how it worked back then.

If you check the `gen7x` dir, you'll see that `genesect` has no drive visible at all, which [seems to be what the games had](https://archives.bulbagarden.net/wiki/File:649MS6.png), and then separately there's a "standard" sprite that has a different color than any of the four drives. I don't know if that one's actually used in-game or if that's a non-standard sprite (in any case it's not listed as a non-standard sprite).

I'm guessing that in `gen8` they changed this, and now the Genesect sprite is never shown in the "no drive" style, and so the "standard" sprite needs to be deleted, seen as how it's already listed in the data file as alias.

Also yes, feel free to make a copy of Appletun, it seems I just totally forgot about that.

As for Arceus, please feel free to make a PR for that too, but maybe you can make it a separate one since I'm looking at the sprites now and I think there may be some small changes I need to make to others. Like my Bug Arceus has red eyes and it shouldn't, so I should just double check them all.

Regarding the project, maybe it'd be good to add that link and then also the link to the project page besides it?

**Comment by PTGigi** [comment]
Yeah, it didn't notice the missing drive either until my second comment, haha. I wonder why they changed it.

I've made a PR for the Appletun and Genesect changes #112 . I'll make a separate Arceus PR when I get the time tomorrow or the day after. 

That sounds like a good idea!

**Comment by msikma** [comment]
Awesome. I'll have a look at it when I've got some time this weekend.

**Comment by msikma** [comment]
I've just merged both your PRs. Thanks for your contribution! I just realized I forgot to add your link to the readme. I'll just do that now.
