### ISSUE TITLE
Gourgeist

### ISSUE THREAD

**Issue by Droidem** [msikma/pokesprite#15]
Hey there!

Thanks for everything you have done for this. This is an amazing project. 

I noticed you finished your update but I can't find the shiny Gourgeist Alternate Forms. Would it be possible for them to be added when you get a chance?

**Comment by 5310** [comment]
I've redrawn alternate sized sprites for the Gourgeist family and can make a PR if they're acceptable:

- [Pumpkaboo](https://github.com/5310/pokesprite/commit/a7a5e4e33fc65021591eeba23973f39475b2c9b7) 
- [Pumpkaboo shiny](https://github.com/5310/pokesprite/commit/ab06f3e06f83f2584b22e6513aa4ccd6e4a2d63a)
- [Gourgeist](https://github.com/5310/pokesprite/commit/d7636da9e1a1549104c096f08416887292df1280)
- [Gourgeist shiny](https://github.com/5310/pokesprite/commit/9d002c1566da5fc015d4f63411ff198af044981a)

**Comment by Droidem** [comment]
I seriously wasn't expecting a response so quickly! They look awesome btw. Thank you for this.

**Comment by 5310** [comment]
I read earlier that @msikma wants to avoid sprites for regular species that aren't in the game as well, so I'll wait until he replies to this issue before making the PR, if at all 😸

**Comment by msikma** [comment]
Well, I recently also added icons for female Hippopotas and Hippowdon, so I guess there's no reason not to add these. The other two were simple recolors and these are actually new sprites, so it might be good to add them as alternate icons, e.g. under `gourgeist-super-alt` instead of `gourgeist-super`.

**Comment by 5310** [comment]
Great! So currently I have the sprites as just `gourgeist-super`, and I've also edited the `data/pkmn.json` and removed the duplicate flag from all six of these new sprites, as well as removed the duplicate files from the `icon/pokemon/regular/duplicates` folder because it _looked_ like that was the intent behind that folder. How should I go about renaming them to `gourgeist-super-alt`, etc? 

My current changes are in this branch: [5310/pokesprite[gourgeist]](https://github.com/5310/pokesprite/commits/gourgeist) 

Alternatively, how about having a sprite-sheet template that only has strictly official sprites, and another that has the unofficial extensions, shinies, rights, alternates et al?

**Comment by 5310** [comment]
Any thoughts on this @msikma? About what I should edit or the non-canonical template?

**Comment by 5310** [comment]
I would still like to help get this issue resolved. If @msikma would reply with what's holding it up or what I should do in terms of structuring my PR.

**Comment by msikma** [comment]
Sorry for being absent. I'll look at this again this weekend.

**Comment by msikma** [comment]
So although I really like your changes, I kind of wanted to make some very small amendments to the icons. I don't have write access to your Gourgeist branch, but I think if you make a PR I should get access (or if not you can grant me access). Also the icons should be PNG32 files, rather than PNG8.

I've made some very small edits to the icons, if you can give me access I'll commit them. Then I'll do some testing to ensure the JSON etc is correct and merge the PR.

**Comment by 5310** [comment]
Oops, I hadn't realized the bit-depth was different. And sorry for the delay.

I've given you collaborator access to the repository. Please let me know if there's any changes I can help with for the PR.

**Comment by 5310** [comment]
Oops, I hadn't realized the bit-depth was different. And sorry for the delay.

I've given you collaborator access to the repository. Please let me know if there's any changes I can help with for the PR.

**Comment by msikma** [comment]
I pushed those changes, let me know what you think. Also, feel free to make a PR. I'll do my final checks then.

**Comment by 5310** [comment]
Will do!

**Comment by msikma** [comment]
Again sorry for absence—going to look at this tomorrow and merge.

**Comment by msikma** [comment]
Finally merged. I noticed some icons weren't updated for shiny yet...then it turns out I just hadn't pulled yet. However, I think Pumpkaboo-Super wasn't updated, so I added that. I'll make a new build now.

**Comment by 5310** [comment]
Oops! I forgot to even add super to the branch! Sorry about that. Also,
hurray!

**Comment by msikma** [comment]
Updated the build.
