### ISSUE TITLE
Shiny star gone

### ISSUE THREAD

**Issue by eldrich** [msikma/pokesprite#19]
Hi,

In [this commit](https://github.com/msikma/pokesprite/commit/055331c70c5781294e1b3b2147ec490269c5ae3d) you got rid of status icons. I actually use Shiny and Pokerus ones. Do you have anything against bringing them back?

Thanks

**Comment by msikma** [comment]
Ohh. I didn't realize anyone would be using them. They were removed because they're UI elements rather than icons. Also because they were practically the only ones that didn't fit the mold of 32x32 or 40x30.

I've attached them here:

![rare_icon](https://cloud.githubusercontent.com/assets/1507745/22907621/47215072-f24a-11e6-9416-5c567274b6df.png) ![anti_pokerus_icon](https://cloud.githubusercontent.com/assets/1507745/22907599/2adcdd50-f24a-11e6-8320-8991b4abf223.png)

Not sure if I should bring them back, since the goal of this repository is to collect and showcase all Pokémon and item icons. If I start including UI as well it would be difficult to decide what goes and what doesn't.

**Comment by msikma** [comment]
I think the best way forward for UI items such as this is to centralize them in a different project. Part of them can be an icon font (since that way Pokémon names can be expressed as PUA Unicode characters), part of them SVG images. I'll be getting started on that sometime soon. For now I'll close this task.

<img width="445" alt="screen shot 2017-08-15 at 16 48 44" src="https://user-images.githubusercontent.com/1507745/29321124-ae4d860c-81d9-11e7-8127-5dea0a6953ba.png">
