### ISSUE TITLE
Pokemon not showing up properly 

### ISSUE THREAD

**Issue by GiacomoLaw** [msikma/pokesprite#30]
I'm using Pokesprite a lot in a project I'm making, but some sprites aren't showing up correctly.

If you go to this site, click on route five at the top, and move up a little, you'll find that the wrong  sprites with the wrong Pokemon.

http://giacomolaw.me/pokefinder/#route5

The sprites are all correctly assigned, and I don't know why it's happening.

![img_9167](https://user-images.githubusercontent.com/9038673/27430483-ac984ff4-5740-11e7-9bc8-f1a4e3f52fe1.PNG)

The code can be found here: https://github.com/GiacomoLaw/pokefinder

Thank you!

**Comment by msikma** [comment]
The only problem I could see is that Pikipek isn't showing up, but that's because it's typoed "Pipipek" in the code...

Have a look at the console, you should see the following warning:

<img width="471" alt="2017-06-23 13 29 30" src="https://user-images.githubusercontent.com/1507745/27466783-08b1d238-5818-11e7-97c9-9da67f5e4ebf.png">

Are there any others that aren't showing up? That's the only one I could find.

**Comment by GiacomoLaw** [comment]
Below that, Grubbin is showing as the third evolution of the water starter. Its not giving an error either

**Comment by msikma** [comment]
I think this is happening because you are hosting the CSS/JS files yourself, but using the live image on Github as well. The mismatch is causing the wrong image to show up because the image coordinates have changed.

The CSS/JS files in your page are version 1.4.6, while the version on Github is 1.4.7 already. I would suggest you update your CSS/JS to 1.4.7 and then also make sure you host the image file on your own server at the correct version. (So that it doesn't break in the future when I update the image.)

**Comment by GiacomoLaw** [comment]
Okay, I will do so. Thanks!
