### ISSUE TITLE
Shiny Cap Pikachu color error / Busted Mimikyu request (and maybe Totems?)

### ISSUE THREAD

**Issue by IAmEmber** [msikma/pokesprite#38]
The shiny Cap Pikachu sprites shouldn't have regular Pikachu's shiny colors. They're based on Ash's (non-shiny) Pikachu and aren't supposed to be obtainable in shiny form, but shiny Partner Cap Pikachu is possible due to an oversight and has the same colors as the non-shiny form (as do the rest if hacked into the game):

![screenshot-2018-2-25 dvza_n3voaaft8k](https://user-images.githubusercontent.com/36805037/36642291-14ea5e50-1a03-11e8-9638-fde94e7a3f7f.png)

Also, can we get a custom sprite for Busted Form Mimikyu? Looks like it's the only non-Totem alternate form without its own sprite. I'm not sure if it's worth the effort making separate sprites for the Totems too, some like Kommo-o already take up most of the image space so I don't know if it's feasible to make them any bigger.

**Comment by msikma** [comment]
Yeah, I'm aware that there are no real shiny forms for Ash's Cap Pikachu, but I made that one just because that's what it should look like if a future game should ever go on to support them. In this case, it's more important to be correct about it than to be completely accurate to the game's rips, in my opinion. Besides, you should never have a shiny Cap Pikachu anyway... 😊

For Busted Form, I don't think that the game has a separate sprite. I try not to make too many custom sprites (I think the only exceptions are the separate sizes we made for Pumpkaboo and Gourgeist). So I'm not sure. It might be useful in e.g. a battle simulator game like Pokémon Showdown, but it's probably of limited use in e.g. spreadsheets because busted form only occurs in battle, right?

**Comment by metaunicorn** [comment]
I wouldn't add the totem sprites, they are just the same but bigger.
That could be made perfectly just with CSS.

For the busted form of Mimikyu it is true it will be a custom sprite but it's not a crazy thing considering that Castform and Aegislash forms that are battle-only also have their official own sprite. For me it makes more sense than having different sprites based on the size (like Pumpkaboo and Gourgeist).

**Comment by msikma** [comment]
I'll give it a shot when I have some more time, regarding Mimikyu.

**Comment by jjmakin** [comment]
Another push for Mimikyu busted form could be that Xerneus has an in-battle only form, and I suppose every mega is supposedly in-battle only too.

**Comment by msikma** [comment]
I'm thinking we should probably not make a Mimikyu custom sprite after all - because Sword/Shield also does not have a custom busted sprite, and the increased detail makes it a bit harder to make a custom sprite that actually looks "good enough" (as if GF themselves made it). But then, I'm not against making one - it's just that I know I'm not good enough to do it myself. Maybe an experienced pixel artist could help out with this at some point.

**Comment by coltongit** [comment]
The actual shiny Cap Pikachu would look exactly like the nonshiny, so just use the standard icon for that if you're needing accuracy. As for Busted Mimikyu/Totems, they should be added in with the SwSh update imo

**Comment by koenigderluegner** [comment]
@coltongit If you know someone who can do it, feel free to tell them to come here

**Comment by route1rodent** [comment]
please let's not mix original designs with custom ones, or at least have a way to differentiate them

**Comment by koenigderluegner** [comment]
> please let's not mix original designs with custom ones, or at least have a way to differentiate them

That's what this flag is for:


is_unofficial_icon | The original (non-shiny) icon has been edited in some way (e.g. Pumpkaboo and Gourgeist). 

Can be found in README on branch node3

**Comment by coltongit** [comment]
@koenigderluegner node3 has been merged into the main branch, so `is_unofficial_icon` should be available on master now.

**Comment by msikma** [comment]
Just to recap, Cap Pikachu isn't "supposed" to be shiny anyway so it's sort of moot, I think - if they ever add shiny variants they'll undoubtedly be like shiny regular Pikachu.

Regarding extra icons (busted mimikyu, totems, etc), I don't want to say I'm not open to suggestions but it'll take really excellent sprite work to make sufficiently credible new icons that fit in seamlessly with the old. I would prefer to stick to official icons only except if they're small edits of official icons, and I think most consumers of this library would too. Gourgeist/Pumpkaboo was sort of an exception to this.

I'm closing this now, but if anyone has suggestions feel free to post here or open a new issue.

**Comment by route1rodent** [comment]
To represent them, it is still possible using pure css on the already available sprites.
So anyone needing them, I'd suggest the following:

Busted Mimikyu: CSS rotation
Totems, Gourgeist/Pumpkaboo: CSS zoom
