### ISSUE TITLE
[Feature Request] Refactor icon names to add veekun/pokedex DB compatibility / interoperability

### ISSUE THREAD

**Issue by route1rodent** [msikma/pokesprite#39]
In an attempt to bring cross-project compatibility, I had to struggle a bit in order to find all images for the Pokemon, Pokemon forms and items listed in the database generated from the well known [veekun/pokedex](https://github.com/veekun/pokedex) project. Still after [my attempt in one of my projects](https://github.com/pokettomonstaa/PokeSource/blob/master/src/importers/pokesprite/import.php) there are a lot of mismatches that I could not solve.

The Veekun Pokedex project is an effort to rip the data directly from the games and is used by numerous projects including https://veekun.com/dex, http://pokeapi.co, https://pokedextracker.com/ (if I am not wrong) and many more (the project has ~300 forks).

Veekun Pokedex has also its cons because the "slugs" or string identifiers they use are neither fully compatible with other well known projects: Pokemon Showdown and Smogon.

My goal is to bring naming consistency to all these projects, including this one, so they will be interoperable.
I think that the best thing to do first is to make this project compatible with Veekun Pokedex, then make that one compatible with Smogon and Showdown, so at the end this project will be compatible with all of them, via the Veekun Pokedex.

What do you think? Are you interested? I will be happy to offer my help in form of pull requests.

**Comment by msikma** [comment]
That sounds great. More compatibility would be very helpful for everyone. I just never really had the time to investigate this, also because I figure it's probably complicated and would require communication with people working on the other projects. But I always thought something like this would be a good idea. The most important thing would be to figure out what changes are needed to make everyone happy.

Would definitely be willing to put in some time for this.

**Comment by metaunicorn** [comment]
I am happy to hear that. Then I will create a script to generate a list detecting what's matching and what needs to be changed :)

**Comment by virtuamon** [comment]
Here is the list: https://github.com/capsulemonsters/foo/wiki/Mismatches-between-Pokesprite-and-Veekun-DB

I'll send you a pull request soon, which should make the icons easier to find using the DB identifiers (name slugs).

**Comment by msikma** [comment]
Closing this for now. There's probably still work to be done in this area, but let's see how things are after the Sword/Shield update is finished.

**Comment by msikma** [comment]
Hi @route1rodent, sorry for reopening this old issue. I'm getting ready to post a big update with Gen 8 support including a ton new item icons. I was wondering if you'd be willing to look into this one more time after I post this update, to see if any new work is needed? Due to how long ago it's been (since [this PR](https://github.com/msikma/pokesprite/pull/40/files)) I've forgotten exactly what your needs are so I'll probably need to do some work after the next update is there, but I'd be glad to do some work to keep things compatible.

**Comment by route1rodent** [comment]
Hey @msikma don't worry, you can go ahead with your Gen 8 changes. Veekun Pokedex project hasn't upgraded to gen 8 yet, so if there are breaking changes in pokesprite master, that's ok for me.

What I recommend you is to release a tag of your current master (maybe version `1.0.0`)
and after you merge gen 8 changes that will become the future version `2.0.0`. So master is always your next version and you have previous version under releases https://github.com/msikma/pokesprite/tags
