### ISSUE TITLE
Meltan and Melmetal sprites

### ISSUE THREAD

**Issue by martimlobao** [msikma/pokesprite#46]
I don't know if these sprites are "official," but the sprites for Meltan and Melmetal are available on Bulbapedia:

https://archives.bulbagarden.net/wiki/File:808MS.png
https://archives.bulbagarden.net/wiki/File:809MS.png

**Comment by msikma** [comment]
I hadn't seen these before. I'm actually quite surprised. The Melmetal icon is 50x30, larger than any other icon (they're all 40x30). I'll need to have a look at where they come from and if they can be considered part of the same series as the ones we have now.

**Comment by Siphonay** [comment]
It seems that larger Pokémon had their icons made bigger and more detailed, from what I noticed while playing the game

**Comment by msikma** [comment]
I'll see if I can arrange a full dump of the icons somewhere. No way to proceed without it.

**Comment by 5310** [comment]
LGPE only has sprites for the Kanto pokémon, Alolan forms, and meltan/melmetal. Would it make sense to update just those pokémon and leave all later generations the same?

**Comment by msikma** [comment]
I don't think it would, because if nothing else there's the issue with them being (apparently) 50x30. But I was thinking of having and maintaining them as a separate set, so that the 40x30 ones remain intact.

**Comment by martimlobao** [comment]
Any update on this? Both Meltan and Melmetal have shinies now, though I don't think there shiny sprites are available anywhere that I know of.

**Comment by msikma** [comment]
Thanks for reminding me about this! I've not actually gone and asked for a full dump yet from the people who have them. I'm going to go and ask around now to see if I can get one.

**Comment by msikma** [comment]
It seems [Pokédex Tracker](https://github.com/pokedextracker) made a shiny version for their app. I was told that I could just take [this image](https://www.spriters-resource.com/nintendo_switch/pokemonletsgopikachueevee/sheet/110762/) and pull it apart if I wanted the sprites, so that's what I did. I've got the images now. They're 68x56. I hope that's correct. I'd really rather just get a nice clean dump directly from the source but it seems no one's around to give me one at the moment.

I'm going to implement these but since they are a different size than the old sprites, some changes will be needed.

**Comment by msikma** [comment]
Another interesting note: I think Pokédex Tracker just creates one giant CSS file to display the sprites. Back when I originally made this project (Aug 2014), this was not possible because not all browsers would accept such huge CSS files. So I solve it with JS. But maybe it's time to change that approach as well!

**Comment by martimlobao** [comment]
Looking at sprites-resource.com, I never realized that there were so many icon variations throughout the games!

**Comment by JRLynch84** [comment]
Was Meltan and Melmetal updated on this project? I can't see them anywhere

**Comment by msikma** [comment]
Hi @JRLynch84, unfortunately I've not been able to do this just yet. But with the SwSh release around the corner I'll prioritize this. I'm going to aim towards getting this repo ready for the new sprite format this weekend!

The reason they Meltan and Melmetal are not here yet is because they're a different size than the others so I'll be using a separate section in the icons directory for them.

**Comment by msikma** [comment]
On another note, purely informational and not related to only those sprites, but I'm planning the following things:

* It seems most people really just use this repo for the icons, rather than for the code to put those icons on a website. So the main focus from here on out will be just on the icons.
* The PHP code for making spritesheets for the icons is extremely outdated. I'm rewriting it as a much smaller JS script.
* Icons will from here on be split into two sections: the original 40x30 icons up to S/M and the newer 68x56 icons for LP/LE and Sw/Sh onwards.
* Originally I thought of making this a monorepo and moving the icons to another directory structure. But a lot of people link to the icons directly (for example, in Google Sheets pages for Pokémon trading), and I can't break compatibility with that so I'll keep everything where it is despite doing some rewriting.

By the way, if anyone has a nice, clean export of the LP/LE icons with no editing and no frills whatsoever, converted as separate png files, please let me know. And same if you are able to get a copy of these icons for Sw/Sh. I'll track them down myself when the game comes out but if anyone can just bring them to me that'd be a nice time saver 😄

I hope this repo can continue to be useful to people after doing some housecleaning and removing all that legacy nonsense.

**Comment by JRLynch84** [comment]
> Hi @JRLynch84, unfortunately I've not been able to do this just yet.

No worries at all! I was looking at the old comments and wasn't sure if it had been done or not :)

And I'm also someone who just uses this resource for the sprites (and it is a GREAT resource for that. I haven't seen anything else that is this good :))

> The reason they Meltan and Melmetal are not here yet is because they're a different size than the others so I'll be using a separate section in the icons directory for them.

I'll be interested to see what format Sword and Shield use (or if they don't have them? That'd be a pain if it was true).

**Comment by msikma** [comment]
> I'll be interested to see what format Sword and Shield use (or if they don't have them? That'd be a pain if it was true).

Or even worse, if they suddenly get canon shiny sprites, then all my work can go into the bin. 😄

I'm just joking, it'd actually be great if they did get them. But I would be a little peeved.

On a side note, I've gotten started on a total rewrite of the sprite generation code. It'll be much simpler, both the script itself and the generated CSS. I'm probably moving that script to a separate repository and using this one just for the sprites (which is really what I should've done when I started this repo...all the way back in 2014).

**Comment by msikma** [comment]
Meltan and Melmetal will be included in the Sword/Shield update, both in 40x30 and 68x56 form.
