### ISSUE TITLE
Shiny Darkrai color error

### ISSUE THREAD

**Issue by Ammako** [msikma/pokesprite#47]
It's not as noticeable when viewing it in its regular size, but I've noticed just now that the darkey grey "outline" color from the regular Darkrai sprite was (I assume unintentionally) left untouched when the shiny sprite was made, making it look a little odd:

![Darkrai](https://puu.sh/C9ZHj/b73b13b4c4.png)

(To the right, how it looks when I use colors from Shiny Darkrai's Gen. 5 sprite.)

**Comment by msikma** [comment]
Hi there. Sorry for replying so late. I'm in the middle of a major update right now and I'm currently going through all the things people have reported over time.

The image you've linked to is gone now, but I've had a look at the sprite. It's true that the outline was left untouched, and it might look a bit weird, but I've kept it that way because every sprite has that same outline regardless of what color is inside, so I felt I couldn't really change it. I think if GF had made this sprite themselves they'd also have stuck with the same outline for each sprite as they have for all regular sprites.

However, maybe the color is a bit too dark and too saturated. If it weren't it probably wouldn't clash.

That said, in the update I'm including a copy of the Gen 7 set with updated size and contrast to fit with Gen 8 icons better, so in that icon the outlines will be a bit darker. Let's see what that looks like when it's there.

**Comment by coltongit** [comment]
Probably will look a bit closer, but it'd be worth tweaking it using the shiny model/texture as a base until it looks correct

**Comment by msikma** [comment]
Does this look better?

![darkrai](https://user-images.githubusercontent.com/1507745/74871338-9844da80-535b-11ea-9dce-445a2df1f0b0.png) ![darkrai](https://user-images.githubusercontent.com/1507745/74871348-9bd86180-535b-11ea-9817-8c2338ae9300.png)

**Comment by Ammako** [comment]
That looks really good!

**Comment by coltongit** [comment]
@msikma Looks good to me. I'd say we put that one in to replace the current and close this once and for all.

**Comment by coltongit** [comment]
Can anyone check to see if the new icon from this issue's been put in place in the repo?

**Comment by Ammako** [comment]
It is, yes.

**Comment by coltongit** [comment]
Thanks msikma. Now that that sprite's been out of the way, we no longer have to deal with the issues that came with the old sprite.
