### ISSUE TITLE
Sprites Not Showing

### ISSUE THREAD

**Issue by Screemm** [msikma/pokesprite#48]
For some reason, I'm unable to display any sprite on my site. I'm using the Laravel framework and followed all the steps in the readme. Sorry if this is something simple. Both files below are included in dex.blade.php.

My meta.blade.php file:
![meta blade php](https://user-images.githubusercontent.com/29709462/50380517-a8ecb880-06a4-11e9-8452-9129096a17c8.PNG)

My dex.blade.php file:
![dex blade php](https://user-images.githubusercontent.com/29709462/50380537-1d275c00-06a5-11e9-90e1-51b3a006f510.PNG)

My footer.blade.php file:
![footer blade php](https://user-images.githubusercontent.com/29709462/50380528-d8032a00-06a4-11e9-9556-aea31c58e2f8.PNG)

**Comment by msikma** [comment]
Hey there, the issue is that `PkSpr.process_dom()` does not wait for the document to finish loading. You must either manually hook make it wait (I'm not sure how Laravel works, but e.g. in jQuery you can do this with a `$(function() { /* here */ });`

Otherwise you could simply add the `PkSpr.process_dom()` line to the bottom of the document, after all the spans with icons have already been sent to the browser. Let me know if that works.

**Comment by Screemm** [comment]
Cool, looks like I just had to move the `PkSpr.process_dom()` down a line in the footer. All fixed. Cheers.

**Comment by msikma** [comment]
Oh wait, right, I misread the source of the footer file completely...

Glad you got it working 🙂
