### ISSUE TITLE
Ribbons

### ISSUE THREAD

**Issue by JosephTico** [msikma/pokesprite#8]
Pokesprite is great, and I love using it. However, there's something it still needs: images for ribbons.

At least the most common ribbons from event Pokémon like the Classic, Premier, Wishing could be implemented on the script.

**Comment by msikma** [comment]
That's a very good point. I'll do some research into this, to see where I can find the ripped ribbon icons from ORAS. (I've got some, but I'm not sure if my collection is complete.)

**Comment by msikma** [comment]
Pretty sure this is a complete XY dump, but I'll still need the ORAS ones.

<img width="447" alt="xy_ribbons" src="https://cloud.githubusercontent.com/assets/1507745/15776257/d15036a6-2986-11e6-931a-7bc655f3586f.png">

**Comment by itsjavi** [comment]
I found them here, not sure if they are complete though

- [X/Y](https://www.serebii.net/xy/ribbons.shtml)
- [OR/AS](https://www.serebii.net/omegarubyalphasapphire/ribbons.shtml)
- [Sun/Moon](https://www.serebii.net/sunmoon/ribbons.shtml)

**Comment by metaunicorn** [comment]
I found another resource for ribbons here, in the PKHeX project: https://github.com/kwsch/PKHeX/tree/master/PKHeX.WinForms/Resources/img/ribbons

**Comment by coltongit** [comment]
Will the ribbons be added in soon?

**Comment by itsjavi** [comment]
also now in gen 8 they are in higher resolution, I think they are not pixel art anymore

**Comment by coltongit** [comment]
> also now in gen 8 they are in higher resolution, I think they are not pixel art anymore

Wonder which Gen we should use for the ribbons, in that case

**Comment by itsjavi** [comment]
I hope we could have both, because some of them don't exist anymore on new gens

**Comment by msikma** [comment]
I'm planning on introducing ribbons to PokéSprite after the Gen 8 update is done. I'm going to see if I can get a clean dump from the games, because all ribbons I'm able to find online have been modified, as they've had empty space trimmed out.

If not I'll probably get them from Bulbapedia because that way I can easily extract all the required meta-information too (name, original game, Japanese title, etc.)

**Comment by coltongit** [comment]
Since the Gen 8 update is out, now's the time to work on getting ribbons to pokesprite.

**Comment by route1rodent** [comment]
@coltongit hmm that's what he said, you repeated the same... but if you mean that you are willing to contribute pls  feel free to open a pull request with your proposal.

otherwise... please avoid these kind of comments. note that every people in this thread get an email or notification or both every time someone comments!

**Comment by coltongit** [comment]
Alright. I'll get to it

**Comment by msikma** [comment]
I already got started on this myself. Fetching the ribbons isn't a difficult task. This data is from Bulbapedia. But I'm still going to check if I can get a cleaner copy that doesn't have trimmed images.

![Screenshot 2020-02-26 at 02 19 20](https://user-images.githubusercontent.com/1507745/75302557-7a391780-583e-11ea-992e-2de18a2375a8.png)

**Comment by coltongit** [comment]
The Bulbapedia images could probably be used first. We can deal with getting ingame rips of everything later. Good to see that the code side of things is getting implemented tok

**Comment by route1rodent** [comment]
in which way are they trimmed? could this work for you? https://www.spriters-resource.com/fullview/123711/
it needs slicing though

**Comment by msikma** [comment]
Unfortunately, this only contains a handful of the newer ribbons. We need a full list of the old ribbons to be able to display any kind of legal ribbon that a Pokémon may carry.

The trimming is a problem because, take [this one](https://bulbapedia.bulbagarden.net/wiki/File:Multi_Ability_Ribbon.png) for example. It's 30x31 pixels. It was originally 32x32 pixels. That means when I expand it back to 32x32 I'm not sure if it's supposed to get 2 pixels up and 1 down, or 1 pixel up and 2 down. (And if they're trimmed, I don't know what other processing might have been done to them.)

But I'm thinking it might not be such a big deal after all. I could possibly just figure it out manually.

**Comment by coltongit** [comment]
> Unfortunately, this only contains a handful of the newer ribbons. We need a full list of the old ribbons to be able to display any kind of legal ribbon that a Pokémon may carry.
> 
> The trimming is a problem because, take [this one](https://bulbapedia.bulbagarden.net/wiki/File:Multi_Ability_Ribbon.png) for example. It's 30x31 pixels. It was originally 32x32 pixels. That means when I expand it back to 32x32 I'm not sure if it's supposed to get 2 pixels up and 1 down, or 1 pixel up and 2 down. (And if they're trimmed, I don't know what other processing might have been done to them.)
> 
> But I'm thinking it might not be such a big deal after all. I could possibly just figure it out manually.

Something to rectify when the ingame rips happen

**Comment by msikma** [comment]
I've done a little bit of preliminary work, see PR #59.

**Comment by msikma** [comment]
Ribbons are now merged: https://msikma.github.io/pokesprite/overview/misc.html
