### ISSUE TITLE
Pokémon SwSh - Crown Tundra DLC - New Icons

### ISSUE THREAD

**Issue by WordeurFTB** [msikma/pokesprite#92]
There are new icons (updates and brand new ones) with the new DLC released today.
Source : https://twitter.com/mattyoukhana_/status/1319454466387726336
![Ek-k0QgXYAA41Ez](https://user-images.githubusercontent.com/23153824/96977798-da8f6e80-151d-11eb-9326-d00ece855abf.png)
(Extension of Issue #91)

**Comment by msikma** [comment]
I've asked for a clean rip of the new sprites so they can be added to the project.

**Comment by msikma** [comment]
Aiming to have the update done this weekend.

**Comment by msikma** [comment]
Little update, I haven't had as much time to work on this as I thought this weekend but I'm about halfway there.

**Comment by msikma** [comment]
Just a couple more. Lots of updates for older Pokémon. There's not that many large Pokémon left without newly updated 68x56 sprites after this.

<img width="1129" alt="Screenshot 2020-11-13 at 22 57 29" src="https://user-images.githubusercontent.com/1507745/99125076-ab8f8880-2603-11eb-90a7-426d6378c4ef.png">

**Comment by msikma** [comment]
PokéSprite has been updated for the second Sword/Shield DLC, Crown Tundra.

The following changes were made:

* Added 5 new Pokémon
* Added 13 new items
* Updated the sprites for newly added Pokémon from previous generations, plus several new forms

In total 104 new shiny sprites were made.

I've also added [a list of Pokémon that have not yet gotten new sprites yet](https://github.com/msikma/pokesprite/blob/master/docs/notes/unupdated-sprites.md) (since they're not included in Sword/Shield yet). This also includes things like all Mega Evolution forms, and other forms that are unavailable in Galar.
